name: Generate Manifest JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Release Info and Generate JSON Manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # List of repository API URLs
          urls=(
            "https://api.github.com/repos/odizinne/globalmicmute/releases/latest"
            "https://api.github.com/repos/odizinne/bigpicturetv/releases/latest"
            "https://api.github.com/repos/odizinne/headsetcontrol-qt/releases/latest"
            "https://api.github.com/repos/odizinne/QMS/releases/latest"
            "https://api.github.com/repos/odizinne/AutoSceneSwitcher/releases/latest"
          )

          # Initialize JSON content
          json_content="["

          for url in "${urls[@]}"; do
            # Fetch the latest release data from the GitHub API
            response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$url")

            # Extract project name and version
            project_name=$(echo $response | jq -r '.url' | awk -F"/" '{print $(NF-2)}')
            version=$(echo $response | jq -r '.tag_name')

            # Initialize download_url as empty
            download_url=""

            # Loop through assets to find the first valid asset that does not contain "linux"
            for asset in $(echo $response | jq -c '.assets[]'); do
              asset_name=$(echo $asset | jq -r '.name')
              if [[ ! "$asset_name" =~ "linux" ]]; then
                download_url=$(echo $asset | jq -r '.browser_download_url')
                break
              fi
            done

            # Only append if a valid download_url was found
            if [[ -n "$download_url" ]]; then
              json_content="$json_content{\"project_name\": \"$project_name\", \"version\": \"$version\", \"url\": \"$download_url\"},"
            fi
          done

          # Finalize the JSON array and write it to a file
          json_content="${json_content%,}]"
          echo $json_content | jq '.' > manifest.json

      - name: Commit and Push Manifest JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Add generated manifest.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
